{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "palette": {
    "text": "#000000",
    "black": "#000000",
    "tooltip-text": "#000000",
    "error": "#e91e63",
    "success": "#00897b",
    "git-bg": "#5682d8",
    "dev-bg": "#66ed5c",
    "staging-bg": "#ea8927",
    "prod-bg": "#ef404c"
  },
  "profiles":{
    "defaults": {
      "font": {
        "face": "MesloLGM Nerd Font"
      }
    }
  },
  "blocks": [
    {
      "alignment": "left",
      "segments": [
        {
          "background": "p:success",
          "background_templates": [
            "{{ if ne .Code 0 }}p:error{{ end }}"
          ],
          "foreground": "p:text",
          "options": {
            "folder_icon": "\u2026",
            "folder_separator_icon": "/",
            "style": "agnoster_short",
            "max_depth": 3
          },
          "style": "diamond",
          "template": " {{ .Path }} ",
          "trailing_diamond": "\ue0c6",
          "type": "path"
        },
        {
          "background": "p:git-bg",
          "foreground": "p:text",
          "leading_diamond": "\ue0c7",
          "options": {
            "branch_icon": "",
            "fetch_status": true,
            "fetch_upstream_icon": true,
            "mapped_branches": {
              "feat/*": "🚀 ",
              "bug/*": "🐛 "
            },
          },
          "style": "diamond",
          "template": " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Staging.Changed) (.Working.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uF046 {{ .Staging.String }}{{ end }} ",
          "trailing_diamond": "\ue0c6",
          "type": "git"
        },
        {
          "background": "p:error",
          "background_templates": [
            "{{if contains \"dev\" .Profile}}p:dev-bg{{end}}",
            "{{if contains \"stag\" .Profile}}p:staging-bg{{end}}",
            "{{if contains \"prod\" .Profile}}p:prod-bg{{end}}"
          ],
          "foreground": "p:text",
          "leading_diamond": "\ue0c7",
          "style": "diamond",
          "template": "  ",
          "trailing_diamond": "\ue0c6",
          "type": "aws"
        },
        {
          "background": "p:error",
          "background_templates": [
            "{{if contains \"dev\" .Name}}p:dev-bg{{end}}",
            "{{if contains \"stag\" .Name}}p:staging-bg{{end}}",
            "{{if contains \"prod\" .Name}}p:prod-bg{{end}}"
          ],
          "foreground": "p:text",
          "leading_diamond": "\ue0c7",
          "style": "diamond",
          "template": "   ",
          "trailing_diamond": "\ue0c6",
          "type": "az"
        },
        {
          "background": "p:error",
          "background_templates": [
            "{{if contains \"dev\" .Project}}p:dev-bg{{end}}",
            "{{if contains \"stag\" .Project}}p:staging-bg{{end}}",
            "{{if contains \"prod\" .Project}}p:prod-bg{{end}}"
          ],
          "foreground": "p:text",
          "leading_diamond": "\ue0c7",
          "style": "diamond",
          "template": " 󱇶 ",
          "trailing_diamond": "\ue0c6",
          "type": "gcp"
        },
        {
          "background": "p:error",
          "background_templates": [
            "{{if contains \"dev\" .Context}}p:dev-bg{{end}}",
            "{{if contains \"stag\" .Context}}p:staging-bg{{end}}",
            "{{if contains \"prod\" .Context}}p:prod-bg{{end}}"
          ],
          "foreground": "p:text",
          "leading_diamond": "\ue0c7",
          "style": "diamond",
          "template": " 󱃾 ",
          "trailing_diamond": "\ue0c6",
          "type": "kubectl"
        },
        {
          "background": "transparent",
          "foreground": "p:success",
          "foreground_templates": [
            "{{ if ne .Code 0 }}p:error{{ end }}"
          ],
          "style": "plain",
          "template": " # ",
          "type": "status",
          "options": {
            "always_enabled": true
          }
        }
      ],
      "type": "prompt"
    }
  ],

  "tooltips_action": "replace",
  "tooltips": [
    {
      "background": "p:error",
      "background_templates": [
        "{{if contains \"dev\" .Profile}}p:dev-bg{{end}}",
        "{{if contains \"stag\" .Profile}}p:staging-bg{{end}}",
        "{{if contains \"prod\" .Profile}}p:prod-bg{{end}}"
      ],
      "foreground": "p:tooltip-text",
      "leading_diamond": "\ue0c7",
      "style": "diamond",
      "template": " {{.Profile}} ",
      "tips": [
        "aws",
        "pulumi",
        "terraform"
      ],
      "type": "aws"
    },
    {
      "background": "p:error",
      "background_templates": [
        "{{if contains \"dev\" .Name}}p:dev-bg{{end}}",
        "{{if contains \"stag\" .Name}}p:staging-bg{{end}}",
        "{{if contains \"prod\" .Name}}p:prod-bg{{end}}"
      ],
      "foreground": "p:tooltip-text",
      "leading_diamond": "\ue0c7",
      "style": "diamond",
      "template": " {{.Name}} ",
      "tips": [
        "az",
        "pulumi",
        "terraform"
      ],
      "type": "az"
    },
    {
      "background": "p:error",
      "background_templates": [
        "{{if contains \"dev\" .Project}}p:dev-bg{{end}}",
        "{{if contains \"stag\" .Project}}p:staging-bg{{end}}",
        "{{if contains \"prod\" .Project}}p:prod-bg{{end}}"
      ],
      "foreground": "p:tooltip-text",
      "leading_diamond": "\ue0c7",
      "style": "diamond",
      "template": " {{.Project}} ",
      "tips": [
        "gcloud",
        "pulumi",
        "terraform"
      ],
      "type": "gcp"
    },
    {
      "background": "p:error",
      "background_templates": [
        "{{if contains \"dev\" .Context}}p:dev-bg{{end}}",
        "{{if contains \"stag\" .Context}}p:staging-bg{{end}}",
        "{{if contains \"prod\" .Context}}p:prod-bg{{end}}"
      ],
      "foreground": "p:tooltip-text",
      "leading_diamond": "\ue0c7",
      "style": "diamond",
      "template": " {{.Context}}{{if .Namespace}}/{{.Namespace}}{{end}} ",
      "tips": [
        "kc",
        "kubectl",
        "kubectx"
      ],
      "type": "kubectl"
    }
  ],
  "transient_prompt": {
    "background": "transparent",
    "foreground": "p:text",
    "foreground_templates": [
        "{{ if eq .Code 0 }}p:success{{ else }}p:error{{ end }}"
    ],
    "template": "{{ if .Interrupted }}<red>^C </>{{ end }}{{.PWD}} # "
  },
  "console_title_template": "{{ .Folder }}",
  "final_space": true,
  "upgrade": {
    "notice": true,
    "auto": false,
    "source": "cdn"
  },
  "version": 4
}
